# Generated by Django 3.1.1 on 2020-09-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200909_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='interval',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
