# Generated by Django 3.1.1 on 2020-09-09 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_link_interval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='interval',
        ),
        migrations.RemoveField(
            model_name='link',
            name='link',
        ),
    ]
