# Generated by Django 3.1.1 on 2020-09-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200909_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='interval',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='link',
            name='link',
            field=models.URLField(default=60),
            preserve_default=False,
        ),
    ]
