# Generated by Django 3.1.1 on 2020-09-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200909_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
